name: fitgymtrack
description: "Cross-platform fitness tracking app for Android and iOS"
publish_to: 'none'

version: 1.0.73+73

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1

  image_picker: ^1.0.4
  path: ^1.8.3


  # ðŸ”§ FIX 1: ALWAYS ON - WakeLock per mantenere schermo acceso durante allenamento
  wakelock_plus: ^1.2.5

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # Navigation
  go_router: ^16.2.1

  # Networking
  dio: ^5.4.3+1
  http: ^1.2.0
  retrofit: ^4.1.0
  connectivity_plus: ^7.0.0

  # JSON Serialization
  json_annotation: ^4.9.0

  # Storage & Persistence
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  
  # 🔐 BIOMETRIC AUTHENTICATION
  local_auth: ^2.1.7  # Autenticazione biometrica (Face ID/Fingerprint)

  # Firebase & Push Notifications
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^19.4.2

  # Date & Time
  intl: ^0.20.2

  # Charts & Visualizations
  fl_chart: ^0.65.0

  # Animations
  lottie: ^3.3.1
  flutter_staggered_animations: ^1.1.1

  # Data processing
  collection: ^1.17.0

  # Device & Platform
  device_info_plus: ^12.1.0
  package_info_plus: ^9.0.0

  # Dependency Injection
  get_it: ^8.2.0

  # ðŸš€ RECOVERY TIMER DEPENDENCIES
  # Audio per feedback sonoro cross-platform
  audioplayers: ^6.0.0

  # ðŸ”§ FIX: Vibrazione con package aggiornato + compatibile
  haptic_feedback: ^0.5.1+1  # Alternativa moderna al vibration package

  # ðŸ’³ STRIPE PAYMENT DEPENDENCIES
  # Stripe SDK principale per Flutter
  flutter_stripe: ^12.0.2

  # ?? BACKGROUND TIMER DEPENDENCIES
  # Notifiche locali per timer in background
  # flutter_local_notifications: ^19.4.2 (già definito sopra)
  # Timezone per gestione notifiche
  timezone: ^0.10.1

  # ðŸ”— URL Launcher per link esterni (Privacy Policy, Terms of Service)
  url_launcher: ^6.2.5
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # ðŸ§ª TESTING DEPENDENCIES
  integration_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  retrofit_generator: ^10.0.5

  flutter_lints: ^6.0.0

  # ðŸ†• BRANDING PACKAGES
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true

  # ðŸ”Š AUDIO ASSETS per timer feedback
  assets:
    - assets/audio/
    - assets/icon/        # ðŸ†• Per le icone personalizzate
    - assets/splash/      # ðŸ†• Per lo splash screen






































































