name: fitgymtrack
description: "Cross-platform fitness tracking app for Android and iOS"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.1

  # 🔧 FIX 1: ALWAYS ON - WakeLock per mantenere schermo acceso durante allenamento
  wakelock_plus: ^1.2.5

  # State Management
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

  # Navigation
  go_router: ^14.1.4

  # Networking
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  connectivity_plus: ^6.0.3

  # JSON Serialization
  json_annotation: ^4.9.0

  # Storage & Persistence
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2

  # Date & Time
  intl: ^0.20.2

  # Device & Platform
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0

  # Charts (per stats)
  fl_chart: ^0.68.0

  # Dependency Injection
  get_it: ^7.7.0

  # 🚀 RECOVERY TIMER DEPENDENCIES
  # Audio per feedback sonoro cross-platform
  audioplayers: ^6.0.0

  # 🔧 FIX: Vibrazione con package aggiornato + compatibile
  haptic_feedback: ^0.5.1+1  # Alternativa moderna al vibration package

  # 💳 STRIPE PAYMENT DEPENDENCIES
  # Stripe SDK principale per Flutter
  flutter_stripe: ^10.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  retrofit_generator: ^9.2.0

  # 🆕 BRANDING PACKAGES
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true

  # 🔊 AUDIO ASSETS per timer feedback
  assets:
    - assets/audio/
    - assets/icon/        # 🆕 Per le icone personalizzate
    - assets/splash/      # 🆕 Per lo splash screen
