// Mocks generated by Mockito 5.4.6 from annotations
// in fitgymtrack/test/unit/bloc/auth_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:fitgymtrack/core/services/session_service.dart' as _i2;
import 'package:fitgymtrack/core/utils/result.dart' as _i3;
import 'package:fitgymtrack/features/auth/models/login_response.dart' as _i6;
import 'package:fitgymtrack/features/auth/models/password_reset_models.dart'
    as _i8;
import 'package:fitgymtrack/features/auth/models/register_response.dart' as _i7;
import 'package:fitgymtrack/features/auth/repository/auth_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSessionService_0 extends _i1.SmartFake
    implements _i2.SessionService {
  _FakeSessionService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResult_1<T> extends _i1.SmartFake implements _i3.Result<T> {
  _FakeResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SessionService get sessionService => (super.noSuchMethod(
        Invocation.getter(#sessionService),
        returnValue: _FakeSessionService_0(
          this,
          Invocation.getter(#sessionService),
        ),
      ) as _i2.SessionService);

  @override
  _i5.Future<_i3.Result<_i6.LoginResponse>> login(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            username,
            password,
          ],
        ),
        returnValue: _i5.Future<_i3.Result<_i6.LoginResponse>>.value(
            _FakeResult_1<_i6.LoginResponse>(
          this,
          Invocation.method(
            #login,
            [
              username,
              password,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Result<_i6.LoginResponse>>);

  @override
  _i5.Future<_i3.Result<_i7.RegisterResponse>> register(
    String? username,
    String? password,
    String? email,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            username,
            password,
            email,
            name,
          ],
        ),
        returnValue: _i5.Future<_i3.Result<_i7.RegisterResponse>>.value(
            _FakeResult_1<_i7.RegisterResponse>(
          this,
          Invocation.method(
            #register,
            [
              username,
              password,
              email,
              name,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Result<_i7.RegisterResponse>>);

  @override
  _i5.Future<_i3.Result<_i8.PasswordResetResponse>> requestPasswordReset(
          String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestPasswordReset,
          [email],
        ),
        returnValue: _i5.Future<_i3.Result<_i8.PasswordResetResponse>>.value(
            _FakeResult_1<_i8.PasswordResetResponse>(
          this,
          Invocation.method(
            #requestPasswordReset,
            [email],
          ),
        )),
      ) as _i5.Future<_i3.Result<_i8.PasswordResetResponse>>);

  @override
  _i5.Future<_i3.Result<_i8.PasswordResetConfirmResponse>> confirmPasswordReset(
    String? token,
    String? code,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmPasswordReset,
          [
            token,
            code,
            newPassword,
          ],
        ),
        returnValue:
            _i5.Future<_i3.Result<_i8.PasswordResetConfirmResponse>>.value(
                _FakeResult_1<_i8.PasswordResetConfirmResponse>(
          this,
          Invocation.method(
            #confirmPasswordReset,
            [
              token,
              code,
              newPassword,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Result<_i8.PasswordResetConfirmResponse>>);

  @override
  _i5.Future<_i3.Result<void>> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<void>>);

  @override
  _i5.Future<bool> isAuthenticated() => (super.noSuchMethod(
        Invocation.method(
          #isAuthenticated,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i6.User?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i5.Future<_i6.User?>.value(),
      ) as _i5.Future<_i6.User?>);
}
